name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]  # Or "main" if your default branch is main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-hello-app .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-hello-app
